//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3615
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tumblott {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    //[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tumblott.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Account に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please input your Tumblr account information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AccountSetting {
            get {
                return ResourceManager.GetString("AccountSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The changes below are applied after restart. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string AppliedAfterRestart {
            get {
                return ResourceManager.GetString("AppliedAfterRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed to load. Retry? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConfirmRetryLoading {
            get {
                return ResourceManager.GetString("ConfirmRetryLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CopyURL {
            get {
                return ResourceManager.GetString("CopyURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do not use the proxy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DoNotUseTheProxy {
            get {
                return ResourceManager.GetString("DoNotUseTheProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Email address に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string GeneralSetting {
            get {
                return ResourceManager.GetString("GeneralSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LoadError {
            get {
                return ResourceManager.GetString("LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Menu に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Network に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Network {
            get {
                return ResourceManager.GetString("Network", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Always confirm when open links に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenLinkConfirm {
            get {
                return ResourceManager.GetString("OpenLinkConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Posts are loaded at once に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PostsAreLoadedAtOnce {
            get {
                return ResourceManager.GetString("PostsAreLoadedAtOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Proxy に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Proxy {
            get {
                return ResourceManager.GetString("Proxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use proxy only for loading images (Useful with an image compression proxy) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProxyOnlyImages {
            get {
                return ResourceManager.GetString("ProxyOnlyImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reload に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Server に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings - Tumblott に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsWindowTitle {
            get {
                return ResourceManager.GetString("SettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show menu bar に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShowMenuBar {
            get {
                return ResourceManager.GetString("ShowMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Thumbnail image size に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ThumbnailImageSize {
            get {
                return ResourceManager.GetString("ThumbnailImageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use default settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UseDefaultSettings {
            get {
                return ResourceManager.GetString("UseDefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Username に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use the proxy below に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UseTheProxyBelow {
            get {
                return ResourceManager.GetString("UseTheProxyBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
